#!/bin/bash
#
# build - compile and optionally install endoh1
#

usage() {
    printf "\nUsage: ./build [-i] [-p prefix] [-u] project [project2 ...]"
    printf "\nWhere:"
    printf "\n\t-i indicates install"
    printf "\n\t-p prefix specifies installation prefix (default ${PREFIX})"
    printf "\n\t-u displays this usage message and exits\n"
    printf "\nNo arguments: build endoh1, configure with prefix=${PREFIX}, build\n"
    exit 1
}

INSTALL=
platform=`uname -s`
if [ "${platform}" == "Darwin" ]
then
  PREFIX=/usr/local
else
  PREFIX=/usr
fi
while getopts "ip:u" flag; do
    case $flag in
        i)
            INSTALL=1
            ;;
        p)
            PREFIX="$OPTARG"
            ;;
        u)
            usage
            ;;
    esac
done
shift $(( OPTIND - 1 ))

[ -f endoh1 ] && [ -f endoh1_color ] || make everything
chmod +x endoh1 endoh1_color

[ "${INSTALL}" ] && {
    [ -d ${PREFIX} ] || sudo mkdir -p ${PREFIX}
    [ -d ${PREFIX}/bin ] || sudo mkdir -p ${PREFIX}/bin
    sudo cp endoh1 endoh1_color ${PREFIX}/bin
}
